export const artworkInventory = [
  {
    id: "DLC-001",
    title: "Coming Back Home",
    titleStatus: "Known from published caption",
    series: "Coming Back Home",
    image: "/instagram/coming-back-home.jpg",
    alt: "DE.LA.COSTA visual work about returning home",
    statement: "Place, return, memory, and the people who keep shaping the work.",
    story: "No matter where the work travels, its emotional center stays close to home. This work anchors the portfolio in return rather than escape.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/p/DVC3Li9jL7a/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-002",
    title: "A Moment to Myself",
    titleStatus: "Known from published caption",
    series: "What We Carry",
    image: "/instagram/moment-to-myself.jpg",
    alt: "Quiet DE.LA.COSTA self-portrait work",
    statement: "Rest, interior life, and the rare space where nothing has to be defended.",
    story: "A pause inside a practice often concerned with public memory. The work makes quietness part of the record rather than an absence from it.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/p/DTNDYYflDGD/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-003",
    title: "Sunday Morning",
    titleStatus: "Known from published caption",
    series: "Coming Back Home",
    image: "/instagram/sunday-morning.jpg",
    alt: "DE.LA.COSTA Sunday morning neighborhood image",
    statement: "Faith, neighborhood rhythm, and an ordinary morning treated as sacred time.",
    story: "A devotional image grounded in the town as it is lived: familiar streets, repeated rituals, and gratitude carried without spectacle.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/reel/DXUv9W9Dwij/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-004",
    title: "The Set?",
    titleStatus: "Known from published caption",
    series: "Civic Memory",
    image: "/instagram/set.jpg",
    alt: "DE.LA.COSTA civic memory work",
    statement: "A visual question about power, public safety, and who gets defined as a threat.",
    story: "The archive turns toward the systems shaping daily life. The question mark matters: it asks the viewer to examine the language institutions use and the experience residents carry.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/reel/DaJ3P_hI1sY/",
    availability: "Exhibition inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-005",
    title: "Game Recognizes Game",
    titleStatus: "Known from published caption",
    series: "Street Notes",
    image: "/instagram/game-recognizes-game.jpg",
    alt: "DE.LA.COSTA street portrait titled Game Recognizes Game",
    statement: "Recognition, respect, and the codes people read without explanation.",
    story: "A compact statement with the rhythm of something spoken on the street. It holds the directness that runs through the wider DE.LA.COSTA archive.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/p/DQNVpALEjdV/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-006",
    title: "Old Town Boogie",
    titleStatus: "Known from published caption",
    series: "Civic Memory",
    image: "/instagram/old-town-boogie.jpg",
    alt: "Old Town Boogie community art gathering",
    statement: "Live printing, music, painting, and truth built in public with the community present.",
    story: "More than event documentation, the work records culture as something produced together. Its subject is the gathering and the response made possible by it.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/reel/DQlHUW7kcuP/",
    availability: "Exhibition inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-007",
    title: "Free the Real",
    titleStatus: "Proposed title — studio confirmation needed",
    series: "Haloed Youth",
    image: "/instagram/freethereal.jpg",
    alt: "DE.LA.COSTA collaborative illustrated work",
    statement: "Friendship, collaboration, and the freedom held inside a shared visual language.",
    story: "A collaborative current runs through the archive. This work places that energy inside Haloed Youth: people held with dignity, presence, and room to become more than a label.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/reel/DRilTZHj-f8/",
    availability: "Licensing / collaboration inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-008",
    title: "Cheo's World",
    titleStatus: "Known from published caption",
    series: "Haloed Youth",
    image: "/instagram/cheos-world.jpg",
    alt: "Illustrated DE.LA.COSTA neighborhood scene",
    statement: "Neighborhood identity, friendship, innocence, and the language of the block.",
    story: "The figures are not symbols placed at a distance. They belong to a lived neighborhood world where memory, tribute, and imagination occupy the same street.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/reel/DYIbb4RSg15/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-009",
    title: "Black and White",
    titleStatus: "Known from published caption",
    series: "What We Carry",
    image: "/instagram/black-and-white.jpg",
    alt: "Black-and-white DE.LA.COSTA community photograph",
    statement: "Community memory, protection, and the emotional weight inside everyday moments.",
    story: "The absence of color becomes emotional language. It records a period when the world felt reduced even while the artist knew more vibrant shades still existed.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/p/DOmPeemkuXb/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
  {
    id: "DLC-010",
    title: "The Value of Everything",
    titleStatus: "Proposed expansion of published caption",
    series: "Ancestral Continuum",
    image: "/instagram/value-of-everything.jpg",
    alt: "Reflective DE.LA.COSTA work about value and discovery",
    statement: "Knowing, not knowing, and the value revealed when certainty falls away.",
    story: "The portfolio closes its first inventory with an open proposition: discovery is not always accumulation. Sometimes it begins when inherited measures of value are released.",
    sourceUrl: "https://www.instagram.com/_de.la.costa_/p/DNHv28BOTWT/",
    availability: "By inquiry",
    medium: null,
    year: null,
    dimensions: null,
    edition: null,
  },
];

export const artworkSeries = ["All", "Coming Back Home", "Haloed Youth", "What We Carry", "Ancestral Continuum", "Civic Memory", "Street Notes"];

export function missingArtworkFields(artwork) {
  return ["year", "medium", "dimensions", "edition"].filter((field) => !artwork[field]);
}
